baseURL = "/" 
title = "Hugo Zzo Theme"
theme = "zzo"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/ngochangjelly"
    email = "ngochang29397@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

